// config-data.js — content & visual identity for the three X-150 configurations.
// Each config gets its own page (volt.html / heat.html / chill.html) using config-page.jsx.

window.ZX_CONFIGS = {
  volt: {
    id: 'volt',
    code: 'ZERO-X-VOLT',
    name: 'VOLT',
    tagline: 'Waste is power.',
    oneline: 'Convert any mixed unrecyclable waste stream into on-site electricity. Replace diesel, eliminate disposal fees, generate verifiable carbon credits — from one container.',
    icon: 'bolt',
    outputIcon: 'bolt',
    outputLabel: 'Electricity',
    conversionDevice: 'Generator Set',
    conversionDesc: 'Producer gas drives a high-efficiency gas genset. Output is grid-quality 3-phase AC — site distribution or grid export.',
    // Color identity — stays within Zero-X palette (yellow + teal)
    primary: '#ffcc32',
    primaryRgb: '255, 204, 50',
    primarySoft: 'rgba(255, 204, 50, 0.18)',
    accent: '#ffd86b',
    secondary: '#1ebec8',
    gradient: 'linear-gradient(135deg, #ffcc32 0%, #ffd86b 50%, #1ebec8 110%)',
    gradientText: 'linear-gradient(110deg, #ffe599 0%, #ffcc32 50%, #1ebec8 110%)',
    haloRgba: '255, 204, 50',
    kpis: [
      ['100', 'kWe', 'Electrical output / unit'],
      ['1.0', 't/d', 'Waste throughput'],
      ['86', '%', 'Cold-gas efficiency'],
      ['24/7', '', 'Dispatchable power'],
    ],
    specs: [
      { label: 'Electrical output', value: '100 kWe', sub: 'per X-150 unit' },
      { label: 'Modular scale', value: 'up to MW', sub: 'parallel units' },
      { label: 'Frequency', value: '50 / 60 Hz', sub: '3-phase AC' },
      { label: 'Island-mode', value: 'Yes', sub: 'black-start capable' },
      { label: 'CHP heat recovery', value: '+280 kWth', sub: 'optional add-on' },
      { label: 'Fuel flexibility', value: '5 streams', sub: 'wood · MSW · sludge · ag · RDF' },
    ],
    problemHead: 'You\u2019re paying twice.',
    problemBody: 'Once to dispose of your waste, again to buy diesel or grid electricity \u2014 and a third time when carbon pricing kicks in.',
    solutionHead: 'VOLT closes the loop.',
    solutionBody: 'Feed waste in, draw electricity out. The same container that takes your trash off the books becomes your on-site power plant.',
    targets: [
      { icon: 'server', t: 'Data centers', d: 'Replace grid + diesel backup with on-site power from waste heat & biomass.' },
      { icon: 'pickaxe', t: 'Off-grid mining', d: 'Diesel replacement for remote operations. Containerized, deployable in days.' },
      { icon: 'factory', t: 'Manufacturing', d: 'Replace industrial electricity with site-generated power from process waste.' },
      { icon: 'users', t: 'Refugee camps', d: 'Humanitarian off-grid power. Convert camp waste into 24/7 electricity.' },
      { icon: 'leaf', t: 'Agricultural', d: 'Process residues, husks, manure \u2014 powering irrigation, cooling, machinery.' },
      { icon: 'pin', t: 'Municipalities', d: 'Diverted landfill becomes the town\u2019s baseload power generator.' },
    ],
  },

  heat: {
    id: 'heat',
    code: 'ZERO-X-HEAT',
    name: 'HEAT',
    tagline: 'Waste is hot.',
    oneline: 'High-temperature thermal output from any waste stream. Replace fossil-fuel boilers in industry, district heating, and process steam.',
    icon: 'flame',
    outputIcon: 'flame',
    outputLabel: 'Thermal energy',
    conversionDevice: 'Boiler',
    conversionDesc: 'Producer gas combusts cleanly in a high-efficiency boiler \u2014 generating saturated steam or pressurized hot water at up to 200 \u00B0C.',
    // Saturated yellow identity (warm tone within brand palette)
    primary: '#ffcc32',
    primaryRgb: '255, 204, 50',
    primarySoft: 'rgba(255, 204, 50, 0.22)',
    accent: '#ffd86b',
    secondary: '#1ebec8',
    gradient: 'linear-gradient(135deg, #f4c400 0%, #ffcc32 50%, #ffe599 100%)',
    gradientText: 'linear-gradient(110deg, #ffe599 0%, #ffcc32 50%, #f4c400 100%)',
    haloRgba: '255, 204, 50',
    kpis: [
      ['650', 'kWth', 'Thermal output / unit'],
      ['1.0', 't/d', 'Waste throughput'],
      ['88', '%', 'Thermal efficiency'],
      ['200', '\u00B0C', 'Peak steam temp'],
    ],
    specs: [
      { label: 'Thermal output', value: '650 kWth', sub: 'per X-150 unit' },
      { label: 'Output medium', value: 'Steam · HW', sub: 'saturated steam or hot water' },
      { label: 'Peak temperature', value: '200 \u00B0C', sub: 'steam side · 90\u00B0C hot water' },
      { label: 'Modular scale', value: 'multi-MWth', sub: 'parallel units' },
      { label: 'Heat recovery', value: 'Economizer', sub: 'integrated stack recovery' },
      { label: 'Fuel flexibility', value: '5 streams', sub: 'wood · MSW · sludge · ag · RDF' },
    ],
    problemHead: 'Industrial heat is the hardest decarbonization problem on earth.',
    problemBody: 'It\u2019s the single largest fossil-fuel use in manufacturing \u2014 burning gas, oil, and coal in boilers and furnaces.',
    solutionHead: 'HEAT replaces them, fuel-flexibly.',
    solutionBody: 'Same boiler-grade steam or hot water output. No gas pipeline. No carbon liability. Drop-in for existing thermal loads.',
    targets: [
      { icon: 'factory', t: 'Process industries', d: 'Pulp, paper, food, chemicals \u2014 replace gas-fired boilers.' },
      { icon: 'coffee', t: 'Breweries', d: 'Brewing requires steam. Run yours from spent grain & site waste.' },
      { icon: 'pin', t: 'District heating', d: 'Municipal heat networks fed from local waste streams.' },
      { icon: 'leaf', t: 'Greenhouses', d: 'Year-round heating in cold climates without LPG or fuel oil.' },
      { icon: 'users', t: 'Hospitals', d: 'Sterilization steam + heating from site waste. Resilient off-grid.' },
      { icon: 'box', t: 'Refugee camps', d: 'Heating in cold-climate humanitarian operations.' },
    ],
  },

  chill: {
    id: 'chill',
    code: 'ZERO-X-CHILL',
    name: 'CHILL',
    tagline: 'Waste is cool.',
    oneline: 'Waste-powered cooling via thermal absorption chillers. Cold storage, HVAC, process cooling \u2014 with zero grid electricity.',
    icon: 'droplet',
    outputIcon: 'droplet',
    outputLabel: 'Chilled water',
    conversionDevice: 'Boiler \u2192 Sorption Chiller',
    conversionDesc: 'Producer gas fires the boiler. Steam drives a single-effect absorption chiller (LiBr\u2013H\u2082O) producing chilled water for refrigeration or HVAC.',
    primary: '#1ebec8',
    primaryRgb: '30, 190, 200',
    primarySoft: 'rgba(30, 190, 200, 0.20)',
    accent: '#6fe8d6',
    secondary: '#ffcc32',
    gradient: 'linear-gradient(135deg, #1ebec8 0%, #6fe8d6 50%, #b3f5ff 100%)',
    gradientText: 'linear-gradient(110deg, #b3f5ff 0%, #6fe8d6 50%, #1ebec8 100%)',
    haloRgba: '30, 190, 200',
    kpis: [
      ['400', 'kW', 'Cooling output / unit'],
      ['0.65', 'COP', 'Thermal coefficient'],
      ['6', '\u00B0C', 'Chilled water min temp'],
      ['Off-grid', '', 'Cooling without grid'],
    ],
    specs: [
      { label: 'Cooling output', value: '400 kW', sub: 'per X-150 unit' },
      { label: 'Coolant', value: 'Chilled water', sub: 'CW supply to site' },
      { label: 'Min temperature', value: '6 \u00B0C', sub: 'down to brine on request' },
      { label: 'Chiller type', value: 'LiBr\u2013H\u2082O', sub: 'single-effect absorption' },
      { label: 'Modular scale', value: '2 MW cooling', sub: 'parallel units' },
      { label: 'Fuel flexibility', value: '5 streams', sub: 'wood · MSW · sludge · ag · RDF' },
    ],
    problemHead: 'Cooling is the fastest-growing electricity demand on earth.',
    problemBody: 'Cold chains collapse without grid stability. Data center cooling is now ~40 % of facility power. Tropical-country hospitals lose vaccines.',
    solutionHead: 'CHILL decouples cooling from the grid.',
    solutionBody: 'Local waste becomes 24/7 chilled water \u2014 no grid, no diesel, no refrigerant leaks at scale. Vaccines, food, and servers stay cold.',
    targets: [
      { icon: 'server', t: 'Data centers (COOLSTACK)', d: 'Off-grid chilled water for hyperscale. Decouple compute growth from grid capacity.' },
      { icon: 'users', t: 'Hospitals', d: 'Critical cold chain for vaccines and blood storage in low-grid regions.' },
      { icon: 'box', t: 'Cold storage (BIOCOOLS)', d: 'Fisheries, dairies, agri-cold-chain in coastal & rural sites.' },
      { icon: 'coffee', t: 'Food processing', d: 'Process cooling for breweries, dairies, slaughterhouses.' },
      { icon: 'leaf', t: 'Greenhouses & ag', d: 'Post-harvest cooling without grid dependency.' },
      { icon: 'pin', t: 'District cooling', d: 'City-wide cooling networks from municipal waste streams.' },
    ],
  },
};

// Shared content reused across all three pages
window.ZX_CONFIG_SHARED = {
  benefits: [
    { icon: 'leaf', t: 'Verifiable carbon credits', d: 'Biochar sequestration + fossil displacement = CDR credits, third-party verified per ton.' },
    { icon: 'recycle', t: 'Disposal cost eliminated', d: 'Replace landfill tipping fees + waste transport with on-site conversion. Bills disappear.' },
    { icon: 'sparkles', t: 'Biochar byproduct', d: 'Stable carbon-rich solid. Sells as soil amendment or sequesters permanently underground.' },
    { icon: 'shield', t: 'Energy independence', d: 'Black-start, island-mode capable. Resilient against grid and supply-chain disruption.' },
  ],
  fundingHead: 'EU + Federal Ministry funding available for qualified pilots.',
  fundingBody: 'Zero-X works with partners to structure non-dilutive grant funding (BMWK, EU Horizon, regional decarbonization funds) for pilot deployments. Up to 60% of CAPEX covered for first-of-kind sites.',
  audiences: ['Hospitals', 'Manufacturing', 'Municipalities', 'Agriculture', 'Refugee Camps', 'Mining', 'Data Centers', 'Cold Chain'],
};
